### ISSUE TITLE
Replace `serve` dependency

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/template#10]
It's got a lot of transitive dependencies, and doesn't sit well with our Brand, yo

**Comment by lukeed** [comment]
Yup, meant for production file server 😄 Existing file paths' content can be updated without restarting, but only if they already existed _before_ `sirv` booted up.

I might add a `--dev` mode in the near future, as I get this request fairly often.

**Comment by lukeed** [comment]
Okay, `sirv@0.2.0` now has a `dev` option and `sirv-cli` has a `--dev` flag. Skips the cache entirely, so files can be adjusted/added/removed without needed to reboot 👍
