### ISSUE TITLE
How to forward requests to a third party server

### ISSUE THREAD

**Issue by MichaelBailly** [sveltejs/template#100]
Hello Svelte team,

I try to use your framework, but the first thing I'd like to do is access to a server API. So I tried to find a way to do some forwarding of any unknown path to a third party server, googled it, but can't find a clue...
I'm looking for a faeture like https://cli.vuejs.org/config/#devserver-proxy (no pun intended, just to express my need).

1/ can you tell me how todo it ?
2/ that should be in the sveltejs/template README, because, well, that is where I looked for it... so I can contribute and add the doc once you enlighten me :-)

**Comment by antony** [comment]
@MichaelBailly Hi Michael,

Github issues isn't the correct place to ask usage questions, it's hard to communicate effectively here. Please find us in the [Discord](https://discordapp.com/channels/457912077277855764/506988048375087114) where we can help you effectively.

Additionally, regarding 2) - it is in the Svelte documentation on the [Svelte Website](https://svelte.dev)

**Comment by MichaelBailly** [comment]
OK so I logged in in discord  and it seems like I can't see anything on the URL you're providing
![image](https://user-images.githubusercontent.com/1465817/70746908-0bf8b480-1d27-11ea-83f5-08ad151353a1.png)

Moreover, when I go to search (the loop in the left bar) and I type "svelte", there is nothing the discord app can find... How am I supposed to find you guys ? :-)

**Comment by mvllow** [comment]
<img width="565" alt="Screen Shot 2019-12-12 at 2 38 35 PM" src="https://user-images.githubusercontent.com/1474821/70747242-30379f80-1ced-11ea-9472-95480f1b04dc.png">
or https://discordapp.com/invite/yy75DKs
