### ISSUE TITLE
recent changes break URL routing

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/template#104]
I have a demo of using the "page" library to do client-side routing in a Svelte app. You can find it at https://github.com/mvolkmann/svelte-routing.

There are two branches here, "master" and "broken". On the master branch you can manually change the browser URL and it will navigate to the correct page. You can enter an unsupported path and the NotFound component is rendered. Neither of these work on the broken branch.

The only difference between these is that master uses a slightly older version of sveltejs/template. The code in the app is identical. I haven't been able to narrow down the problem yet, but I wanted to post this to warn others. Something in the latest version of the template is breaking routing.

**Comment by mvllow** [comment]
This is caused by the start script. For some reason the start script removed the `--single` argument.

This can be fixed here:

```js
// rollup.config.js

function serve() {
  let started = false;

  return {
    writeBundle() {
      if (!started) {
        started = true;
				
        // Added --single here
        require('child_process').spawn('npm', ['run', 'start', '--', '--dev', '--single' ], {
          stdio: ['ignore', 'inherit', 'inherit'],
          shell: true
        });
      }
    }
  };
}
```

**Comment by Conduitry** [comment]
You should change the `start` script itself to include `--single`, not just what's called by `npm run dev`.

SPA mode was disabled by default in #88/#90, and a section was added to the readme.

**Comment by mvolkmann** [comment]
Thanks @Conduitry!
