### ISSUE TITLE
Unit and e2e test for template

### ISSUE THREAD

**Issue by blacksonic** [sveltejs/template#118]
What do you think about the test configuration in the template?
For example jest and cypress.
Using a template, I would not want to have a cognitive load when installing plugins for tests

**Comment by pngwn** [comment]
This template is intended to be the bare minimum needed to get started with svelte, it is not a production-ready template. We want to leave the finer details, such as testing, down to the user.  With this in mind, we don't want to endorse any particular testing library, especially when the experience with those libraries isn't as good as it could be.

[There is an initiative to create a CLI](https://github.com/sveltejs/svelte/issues/3103) that could cover this use case.

**Comment by blacksonic** [comment]
I can't find a production-ready template for Svelte, where else should it be if not in the template the official cli generates?

Jest is a popular and usable solution, what's the problem with "all" of them?

I'm a bit disappointed that this issue is closed without discussion.

**Comment by pngwn** [comment]
There have been a number of issues and PRs on this topic in the past, we need to close issues that won’t be actioned in order to keep the issue list as clean as possible. This is something we want to address in the future but simply adding jest or cypress isn’t something we are willing to do right now.

**Comment by frederikhors** [comment]
> I can't find a production-ready template for Svelte, where else should it be if not in the template the official cli generates?
> 
> Jest is a popular and usable solution, what's the problem with "all" of them?
> 
> I'm a bit disappointed that this issue is closed without discussion.

You can't discuss what is already discussed (and a lot) here. Simply search in issues.

This is a starter template.

Can you fork and create one like https://github.com/blacksonic/svelte-template?

**Comment by blacksonic** [comment]
Ok...is there a place for discussion on this?
