### ISSUE TITLE
Svelte Scripts

### ISSUE THREAD

**Issue by andrelmlins** [sveltejs/template#119]
I created the Svelte Scripts project to create an abstraction of settings to start a Svelte project.

https://github.com/andrelmlins/svelte-scripts

Would you be interested in inserting it in the template? Or place the project within the github organization.

**Comment by antony** [comment]
Hi @andrelmlins 

I'm struggling to see how this differs from the normal way of creating a svelte app?

`npm degit sveltejs/template` for example?

**Comment by andrelmlins** [comment]
Hello @antony , this library removes abstract settings. The settings for starting and building a project are within the library. Along with settings for testing.

The template would look like this

https://github.com/andrelmlins/svelte-scripts/tree/master/template

**Comment by pngwn** [comment]
We don’t really want to abstract the settings. These should be starters that can then be modified easily by users. We don’t want to hide configs in this way.
