### ISSUE TITLE
When i want use socket.io-client , But it's look like packaged some node.js modules.

### ISSUE THREAD

**Issue by MiYogurt** [sveltejs/template#12]
```
import io from "socket.io-client";    
```

```
main.js:8 Uncaught ReferenceError: os is not defined  at main.js:8
```

If i use dist/socket.io

```
import io from "socket.io-client/dist/socket.io";
```

```
Uncaught TypeError: Cannot read property 'Buffer' of undefined
    at Object.<anonymous> (socket.io.js:6)
```

If i want parcel the lib run in browser 。 how to ? thanks.

**Comment by MiYogurt** [comment]
emmmm. i found a webpack build sample in https://github.com/socketio/socket.io/blob/2.0.3/examples/webpack-build/support/webpack.config.json-parser.js

**Comment by MiYogurt** [comment]
i config alias plugins , still have as same as problem

```
    alias({
		debug: process.cwd() + '/noop.js',
		'socket.io-parser': process.cwd() + '/node_modules/socket.io-json-parser/index.js'
    }),
```

```
main.js:8 Uncaught ReferenceError: fs is not defined
```

**Comment by djorborn** [comment]
I have not found a way to import socket.io but you can trick parcel by adding a small script in your index.html head.
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sockets</title>

<!-- Trick Part One -->
  <script id="s"></script>
<script>
  document.getElementById('s').src = "socket.io/socket.io.js"
</script>
<!-- End -->

</head>
<body>
  <div id="app"></div>

<!-- Trick Part Two -->
  <script defer>
    var socket = io();
    socket.on('open', message => console.log(message))
  </script>
<!-- END -->

<!-- Parcel src -->
  <script defer src="./index.js"></script>
</body>
</html>
```
It has been working for me so far, maybe someone will figure something better out soon.

**Comment by MiYogurt** [comment]
@djorborn 3q your solution 😄

**Comment by ericsartor** [comment]
@djorborn 's solution didn't work for me.  My TypeScript project still complained about `socket` not being defined.

I've found a solution to this that suits my needs wonderfully.

I let parcel handle building my app into the dist folder, then when I serve it, I simply modify the HTML file to add in the Socket IO script:

	app.get('/', (req, res) => {
	    const fileLocation = path.normalize(__dirname + '../../../dist/index.html');
	    const indexContent = fs.readFileSync(fileLocation, { encoding: 'utf8' });
	    const tagToInsertAfter = '<body>';
	    const locationToInsertSocketScript = indexContent.indexOf(tagToInsertAfter) + tagToInsertAfter.length;
	    const indexWithSocketScript = indexContent.slice(0, locationToInsertSocketScript) +
	        '<script src="/socket.io/socket.io.js"></script>' +
	        indexContent.slice(locationToInsertSocketScript);
	    
	    fs.writeFileSync(fileLocation, indexWithSocketScript, { encoding: 'utf8' });

	    res.sendFile(fileLocation);
	});

This is just for development for me, in production you could just run this process once when you start the server after updating your static assets that parcel builds.

This is probably not an ideal solution, but it's the only thing that's worked for me using Parcel to develop with TypeScript.
