### ISSUE TITLE
Would there be any advantage in upgrading to Rollup 2?

### ISSUE THREAD

**Issue by SteveALee** [sveltejs/template#120]
I see there are breaking changes but also apparently some goodies too.

**Comment by Conduitry** [comment]
It'd probably be a good idea, because I imagine Rollup 1 isn't going to be maintained any longer. The main breaking change would probably be dropping support for Node 8, which is end-of-life so I don't see that as much of an issue.

**Comment by zqianem** [comment]
Specifically, Rollup 2 fixes watch issues like https://github.com/rollup/rollup/issues/1666 via https://github.com/rollup/rollup/issues/2988. While this doesn't seem to affect too many setups, having a working live-reload is important for first impressions, imo. Is there anything blocking #123 currently?

**Comment by frederikhors** [comment]
The question is WHY NOT? IMO.

Anyway no problem at all, I'm already using it.

**Comment by Conduitry** [comment]
Yeah we do want to update to Rollup 2 probably. I don't think losing Node 8 support is a show-stopper. Right now I'm waiting for https://github.com/rollup/plugins/issues/304 to settle down though. A fix has been merged in, but not yet released.
