### ISSUE TITLE
CSS autoprefixing not included by default

### ISSUE THREAD

**Issue by darajava** [sveltejs/template#129]
Not including autoprefixing in the CSS is a huge barrier to having this production ready, as output doesn't work on inferior browsers even if you use something as simple as flexbox.
 
**Describe the solution you'd like**
It would be nice to have CSS rules autoprefixed in the rollup config. I could not find a way to do this via the docs or by reading.

**Describe alternatives you've considered**
I tried really hard to get autoprefixing working, but couldn't. I am now faced with either having to migrate to webpack, where it is documented better, or to manually add the prefix names.

**How important is this feature to you?**
This is quite important for me since you get this out of the box with React, and I feel important for Svelte to be taken seriously as a production tool.

**Comment by antony** [comment]
Hi @darajava. To add autoprefixing, install the `svelte-preprocess` plugin - autoprefixing is documented on their readme: https://github.com/kaisermann/svelte-preprocess

This is not something we necessarily want to include in the template (it is designed to be the very bare minimum) but something which would make a nice recipe for the [svelte society site](https://github.com/svelte-society/site) so linking it there.

**Comment by darajava** [comment]
My apologies, the issue I was looking at was in fact a bug in Safari. Thanks!
