### ISSUE TITLE
watch does not start

### ISSUE THREAD

**Issue by PierBover** [sveltejs/template#133]
So I cloned the repo, installed dependencies, and when doing `npm run dev` nothing happens...

```
Piers-iMac:template-master pier$ npm run dev

> svelte-app@1.0.0 dev /Users/pier/Downloads/template-master
> rollup -c -w

Piers-iMac:template-master pier$
```

**Comment by PierBover** [comment]
It's some issue with `livereload`. I commented this line in `rollup.config.js` and it works now:

```
!production && livereload('public'),
```

**Comment by sansnom** [comment]
Same here. Also in livereload rollup plugin: https://github.com/thgh/rollup-plugin-livereload/issues/46

**Comment by avimar** [comment]
I had livereload working, and it seems to sometimes work, but I can't figure out when and why. There's no longs I can find.

It simply shows the command to run and then stops. It's not simply that livereload doesn't work, it's that it stops the entire process from even compiling the first time.

**Comment by avimar** [comment]
Happens consistently for me when I'm running livereload in another window, too. Port conflict.

**Comment by Daniel-Knights** [comment]
> It's some issue with `livereload`. I commented this line in `rollup.config.js` and it works now:
> 
> ```
> !production && livereload('public'),
> ```

This works for me. If I comment it whilst it's running on 5000, it switches to a random port like 58603 and works fine.

**Comment by avimar** [comment]
There's a port conflict with a second liverload session running in a different CLI.

https://github.com/thgh/rollup-plugin-livereload/issues/51

**Comment by Daniel-Knights** [comment]
Managed to fix the issue this way (in the CLI):

```bash
lsof -i :5000
```
Grab the PID and kill:
```bash
kill -9 35587
```

**Comment by basilikode** [comment]
I was also failing to see the app on [](http://localhost:5000). In my case the port is used by a docker process.
I don't want to kill that so I've fixed the issue by changing the line `"start": "sirv public"` in `package.json` to `"start": "sirv public --port 5050"`. I've opened #159 to add this info on the README.md

**Comment by antony** [comment]
This is fixed by https://github.com/thgh/rollup-plugin-livereload/pull/24

once that is merged, we'll update the template with the new version.
