### ISSUE TITLE
Why need Username in degit ?

### ISSUE THREAD

**Issue by NaokiM03** [sveltejs/template#139]
I'm sorry, I'm not familiar with degit.

```
# npx degit sveltejs/templete .
npx: installed 1 in 1.046s
Username for 'https://github.com':
```

No need for other templete.
For example, `template-webpack` and `component-template` .

```
# npx degit sveltejs/template-webpack .
npx: installed 1 in 1.074s
> cloned sveltejs/template-webpack#master
```

```
# npx degit sveltejs/component-template .
npx: installed 1 in 1.567s
> cloned sveltejs/component-template#master
```

**Comment by antony** [comment]
This isn't the correct place for support issues, and this isn't the `degit` project. You need to ensure your machine is correctly authorised with github and that your private keys are set up correctly - see the degit and github documentation

**Comment by NaokiM03** [comment]
It's hard to understand why need GitHub authentication to use templete, but if that's the policy, it's understandable.
I'm not asking you how to authenticate to GitHub, I'm asking you why you need it for this project.

**Comment by NaokiM03** [comment]
I'm really sorry. I just tested it again and I didn't need to authenticate. I don't know why, but I'm sorry for the hassle.

**Comment by NaokiM03** [comment]
I read the degit source and found that I was in the wrong place to put up the Issue. Sorry about that.

**Comment by mvllow** [comment]
> I'm really sorry. I just tested it again and I didn't need to authenticate. I don't know why, but I'm sorry for the hassle.

your comment had a typo in `npx degit sveltejs/templete` where "templete" should be "template"

because `sveltejs/templete` (typo version) is not a public repository that could be why it's asking for authentication. hope that helps 🥰

**Comment by NaokiM03** [comment]
Thank you. Time has melted……

**Comment by pfsquirrel** [comment]
I tried it from memory and hit the same thing, but my memory was at fault. This doesn't work:

`npx degit svelte/template new-project`

This does work:

`npx degit sveltejs/template new-project`

I just hope nobody in the `svelte` organization goes to the Dark Side and tries to host malicious versions of SvelteJS. 🏴‍☠️
