### ISSUE TITLE
Prevent setupTypeScript.js from deleting the scripts folder if it's not empty

### ISSUE THREAD

**Issue by opensas** [sveltejs/template#144]
Prevent setupTypeScript.js from deleteing the scripts folder if it's not empty

The setupTypeScript.js is used to add TypeScript support to an application created with the `npx degit sveltejs/template svelte-typescript-app` command, as stated [here:](https://svelte.dev/blog/svelte-and-typescript#Try_it_now)

It removes the scripts folder after adding TypeScript support to the current Svelte application, like this:

```javascript
// Delete this script, but not during testing
if (!argv[2]) {
  // Remove the script
  fs.unlinkSync(path.join(__filename))
  // Remove the scripts folder
  fs.rmdirSync(path.join(__dirname))
}
```

If the user added any script to that folder it would also be deleted.

Moreover, with this modification, the same script could be used to add support to an existing Svelte application, like this:

```shell
$ cd existing-svelte-app

$ npx degit sveltejs/template/scripts scripts

$ node scripts/setupTypeScript.js
Converted to TypeScript.
```

In case the scripts folder is not empty after removing setupTypeScript.js, we'll just leave it ther (perhaps showin a message like `scripts folder not empty`)

If you are ok with this I can create a PR

**Comment by orta** [comment]
Good call, I'd accept that PR 👍

**Comment by opensas** [comment]
done: https://github.com/sveltejs/template/pull/147
