### ISSUE TITLE
Unable to import typescript interfaces

### ISSUE THREAD

**Issue by jnordberg** [sveltejs/template#146]
Using this template with typescript I'm getting "name-is-not-exported-by-module" errors when trying to import interfaces from external modules. ~Was able to solve it by downgrading the rollup commonjs plugin as suggested in this issue: https://github.com/pyoner/svelte-typescript/issues/23~ Actually not, that was a red herring. Downgrading caused my build to hang indefinitely and a stale bundle was served making it look like it worked..

**Comment by benmccann** [comment]
Make sure to `import type`: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports

**Comment by jnordberg** [comment]
Thanks, that worked. When using the standard way of importing types in Vue et all it works fine. Is this a fundamental limitation of svelt or something that could be improved?

**Comment by benmccann** [comment]
I'm really not sure. I think `type` would be the preferred way to do it in either case, but it does seem funny that it works differently in Svelte

I think that this is related to https://github.com/sveltejs/svelte-preprocess. If you want to be a baller you could ask over in that repo why that is and then update the TypeScript FAQ: https://github.com/sveltejs/svelte/blob/master/site/content/faq/500-what-about-typescript-support.md
