### ISSUE TITLE
Unable to serve localhost

### ISSUE THREAD

**Issue by RafaelLiendo** [sveltejs/template#153]
Following the docs to create a new App and run on localhost
```cmd
npx degit sveltejs/template svelte-app
cd svelte-app
npm install
npm run dev
```
```cmd
  Your application is ready~! �

  - Local:      http://localhost:5000
  - Network:    Add `--host` to expose
```
but, there's going on localhost:5000

Maybe another process using the same port? let's see...
```
netstat -ano | findstr :5000
```
Nope, no other process there...

Try to change the port?
```diff
"scripts": {
  "build": "rollup -c",
  "dev": "rollup -c -w",
-  "start": "sirv public",
+  "start": "sirv public --port 4200",
  "validate": "svelte-check"
},
```
```
npm run dev
  Your application is ready~! �

  - Local:      http://localhost:4200     
  - Network:    Add `--host` to expose    
```
Nope =/ still nothing.

Maybe run as Admin? Nope =/

Run with --host? 
```diff
"scripts": {
  "build": "rollup -c",
  "dev": "rollup -c -w",
-  "start": "sirv public",
+  "start": "sirv public --host",
  "validate": "svelte-check"
},
```
```
  Your application is ready~! �

  - Local:      http://0.0.0.0:5000       
  - Network:    http://192.168.15.22:5000 
```
Yes! Finally works on http://192.168.15.22:5000, but http://0.0.0.0:5000 still dosen't

I've also tried this solution
https://github.com/sveltejs/template/issues/148#issuecomment-663937048
but didn't work =/

I'm using:
OS: windows 10 64
Node: v12.18.3

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

**Comment by RafaelLiendo** [comment]
Sorry, but this is not a StackOverflow question. 
The sirv-cli package is not working as intended. It fails to serve on localhost.

**Comment by baldscone** [comment]
Im with @RafaelLiendo - this is a legit bug. I follow the instructions:

`npx degit sveltejs/template svelte-app
cd svelte-app
npm install
npm run dev
`
and I get a blank page with 404s for all the files:

`
 Your application is ready~! 🚀

  - Local:      http://0.0.0.0:5000
  - Network:    http://192.168.1.215:5000

────────────────── LOGS ──────────────────

  [23:38:12] 404 ─ 1.14ms ─ /build/bundle.css
  [23:38:12] 404 ─ 0.09ms ─ /build/bundle.js
  [23:38:15] 404 ─ 0.15ms ─ /build/bundle.css
  [23:39:12] 404 ─ 0.12ms ─ /build/bundle.css
  [23:39:12] 404 ─ 0.11ms ─ /build/bundle.js
  [23:39:14] 200 ─ 1.43ms ─ /
  [23:39:14] 404 ─ 0.13ms ─ /build/bundle.css
  [23:39:14] 404 ─ 0.08ms ─ /build/bundle.js
  [23:39:14] 200 ─ 0.32ms ─ /favicon.png
`

**Comment by angel-manuel** [comment]
`http-server` worked for me, just installed it and changed `sirv` for `http-server` on `npm run start`
