### ISSUE TITLE
Rollup console log covering Sirv's

### ISSUE THREAD

**Issue by anonimusprogramus** [sveltejs/template#16]
When I run
`npm run dev`

As soon as appeared Sirv's: 
`Your application is ready~! 🚀`
`- Local:      http://localhost:5000`
`- Network:    http://192.168.0.200:5000`

then appeared Rollup's:
`rollup v1.4.1`
`bundles src/main.js → public/bundle.js...`
`created public/bundle.js in 240ms`
`[2019-03-06 17:19:39] waiting for changes...`

Please let Sirv's console log appear so we know what port Svelte's running.

**Comment by lukeed** [comment]
You can add this to your Rollup config:

```js
watch: {
  clearScreen: false
}
```

Rollup output will still appear but it won't reset your terminal, allowing you to still see the port sirv I using.

**Comment by anonimusprogramus** [comment]
Thanks.
