### ISSUE TITLE
Use svelte-app-ts command instead provide setupTypeScript.js file?

### ISSUE THREAD

**Issue by lamualfa** [sveltejs/template#166]
I thought wouldn't it be better to provide a command to create a project Typescript like `npx degit sveltejs/template svelte-app-ts` than to provide a script (`scripts/setupTypeScript.js`) for migrating?  the goal is to prevent people from changing any configuration in the `scripts/setupTypeScript.js` file due to their ignorance of it. it would also be useless if the people using it wanted to use pure Javascript as the language of their project.

Thanks

**Comment by benmccann** [comment]
The reason we didn't create another repo or branch is that it would be too hard for us to maintain and keep in sync. People can easily remove `setupTypeScript.js` if they don't need it

**Comment by lamualfa** [comment]
Oh, I'm sorry. I think `svelte` uses an internal script which is run using `npx` as `routify` does. It turns out that svelte uses `degit` to install (clone) the template.
