### ISSUE TITLE
Sirv didn't hot-reload

### ISSUE THREAD

**Issue by anonimusprogramus** [sveltejs/template#17]
After running `npm run dev`, changing to `Helllooo {name}!!` in `App.svelte` didn't trigger hot reload, I had to manually refresh browser.

Tried similar http server: `npm install live-server --save-dev`, and edit `package.json` scripts, **it works**

**Comment by lukeed** [comment]
Sirv doesn't hot reload. It's just a file server

**Comment by anonimusprogramus** [comment]
Ups, i didn't know. Sorry. TIL.

**Comment by lukeed** [comment]
All good! I'm (slowly) working on a HMR utility that can be used here

**Comment by iambudi** [comment]
> Tried similar http server: `npm install live-server --save-dev`, and edit `package.json` scripts, **it works**

Care to mention how to call live-server on the package.json?

**Comment by anonimusprogramus** [comment]
After installing `live-server`, edit `package.json`,

change
`"start:dev": "sirv public --dev"`
into
`"start:dev": "live-server public"`

And then run `npm run dev` as usual.

**Comment by iambudi** [comment]
@anonimusprogramus Thank you, works nicely.
