### ISSUE TITLE
sirv does not support 206 partial content

### ISSUE THREAD

**Issue by lukasIO** [sveltejs/template#18]
I started out working with this template (v3) and had to change sirv to a different static server.
On chrome *seeking, setting time etc.* of videos apparently only works if the (static) video files return a 206 Partial Content response. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206)
Not sure if sirv wants to support this, but would imho be nice if the "official" starting template would support the partial content response out of the box.

**Comment by lukeed** [comment]
Hey, thanks~! Completely forgot about this. 

Since `sirv` is currently undergoing major changes anyway (include HTTP/2 support), I'll work this in.

**Comment by lukeed** [comment]
This can be closed, as `sirv@0.3.0` now responds to ranged/partial requests appropriately 

Thanks for the reminder :)

**Comment by lukasIO** [comment]
@lukeed nice, should we update the version in the package.json then?

**Comment by lukeed** [comment]
Semver will resolve to the latest since it was a minor bump

**Comment by Conduitry** [comment]
`^0.2.3` doesn't match `0.3.0`. Versions whose major number is zero are treated differently. In 0.x.y, x is assumed to be for major changes and y for minor/patch ones.

**Comment by lukeed** [comment]
Ah, didn't know about the 0-major exception. TIL
