### ISSUE TITLE
Error: Identifier directly after number (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by SARFEX** [sveltejs/template#193]
`npx degit sveltejs/template svelte-app`
`cd svelte-app`
`npm install`
`npm run dev`

```
d:\Projects\svelte-app>npm run dev

> svelte-app@1.0.0 dev d:\Projects\svelte-app
> rollup -c -w

rollup v2.33.3
bundles src/main.js → public\build\bundle.js...
[!] Error: Identifier directly after number (Note that you need plugins to import files that are not JavaScript)
src\App.css (1:13)
1: main.svelte-1tky8bj{text-align:center;padding:1em;max-width:240px;margin:0 auto}h1.svelte-1tky8bj{color:#ff3e00;text-transform:uppercase;font-size:4em;font-weight:100}@media(min-width: 640px){main.svelte-1tky8bj{max-width:none}}
                ^
Error: Identifier directly after number (Note that you need plugins to import files that are not JavaScript)
    at error (d:\Projects\svelte-app\node_modules\rollup\dist\shared\rollup.js:5253:30)
    at Module.error (d:\Projects\svelte-app\node_modules\rollup\dist\shared\rollup.js:9821:16)
    at tryParse (d:\Projects\svelte-app\node_modules\rollup\dist\shared\rollup.js:9702:23)
    at Module.setSource (d:\Projects\svelte-app\node_modules\rollup\dist\shared\rollup.js:10128:19)
    at ModuleLoader.addModuleSource (d:\Projects\svelte-app\node_modules\rollup\dist\shared\rollup.js:18289:20)
    at ModuleLoader.fetchModule (d:\Projects\svelte-app\node_modules\rollup\dist\shared\rollup.js:18345:9)
    at async Promise.all (index 1)
    at ModuleLoader.fetchStaticDependencies (d:\Projects\svelte-app\node_modules\rollup\dist\shared\rollup.js:18370:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (d:\Projects\svelte-app\node_modules\rollup\dist\shared\rollup.js:18347:9)
```

**Comment by Conduitry** [comment]
I can't reproduce this. That error sounds like you don't have the proper CSS plugin installed and configured, but the current template has `rollup-plugin-css-only` in its [`rollup.config.js`](https://github.com/sveltejs/template/blob/master/rollup.config.js).

**Comment by SARFEX** [comment]
I have tried even on a clean installed Node 14.15.1, and I have same problem on different PC.
Windows 10 in both cases

**Comment by SARFEX** [comment]
And I have no problems when I use the older template from Oct 6, 2020
https://github.com/sveltejs/template/tree/431bd4d58e59b46ebfa1f4fc2c1ab55853fc1521

**Comment by Conduitry** [comment]
I just tried this on a fresh Windows 10 sandbox with Node 14.15.1 and could not reproduce it there either.

**Comment by henrycz** [comment]
hi, i'm new to svelte, i have the same problem ... what can i do?.
![errorfinal](https://user-images.githubusercontent.com/9146561/100922961-824c7480-34ac-11eb-9876-c04a22fdd647.png)

**Comment by mattsahr** [comment]
Me too.  Same problem.  Windows 10.
I deleted node_modules, reinstalled everything.  Problem persists.

![svelte_npm_run_dev_error](https://user-images.githubusercontent.com/556467/100923999-52b75f80-34e0-11eb-846d-ca19d0c4d18d.png)

**Comment by lukeed** [comment]
Please note that if you've upgraded to `rollup-plugin-svlete@7.x` you'll need to include a Rollup plugin that deals with CSS – hence the major version bump.

You can see the relevant changes to the template here: https://github.com/sveltejs/template/pull/185/files

**Comment by mattsahr** [comment]
I hit this problem on the latest version of Svelte, not an upgrade, a clean new install.

**Comment by lukeed** [comment]
Sorry to ask, but is `css` actually attached to the `plugins: [ ... ]` array?

**Comment by henrycz** [comment]
> Encontré este problema en la última versión de Svelte, no en una actualización, una nueva instalación limpia. Incluso...
> 
> package.json
> "rollup-plugin-css-only": "^ 3.0.0",
> 
> rollup.config.js
> importa css desde 'rollup-plugin-css-only';


what would be the mistake?
where is it corrected?

**Comment by henrycz** [comment]
> > Encontré este problema en la última versión de Svelte, no en una actualización, una nueva instalación limpia. Incluso ...
> > package.json 
> > "rollup-plugin-css-only": "^ 3.0.0",
> > rollup.config.js 
> > importa css desde 'rollup-plugin-css-only';
> 
> cual seria el error?
> donde se corrige?


Should I delete it? .... please I'm new to svelte, I don't know what to do ...

**Comment by henrycz** [comment]
> I hit this problem on the latest version of Svelte, not an upgrade, a clean new install. Including...
> 
> package.json
> "rollup-plugin-css-only": "^3.0.0",
> 
> rollup.config.js
> import css from 'rollup-plugin-css-only';


Should I delete it? .... please I'm new to svelte, I don't know what to do ...

**Comment by henrycz** [comment]
> Please note that if you've upgraded to `rollup-plugin-svlete@7.x` you'll need to include a Rollup plugin that deals with CSS – hence the major version bump.
> 
> You can see the relevant changes to the template here: https://github.com/sveltejs/template/pull/185/files


I have followed the guide but it does not solve my error

**Comment by antony** [comment]
For usage questions, please come and chat to us in [discord](https://svelte.dev/chat), you'll get a much quicker answer than trying to reply to bug reports.

**Comment by antony** [comment]
I've tried this on Linux with node v14 and it works as expected.

Do any of you fancy trying this on WSL?

**Comment by mattsahr** [comment]
I found one solution for this. 

In `rollup.config.js` you can add `emitCss: false` to the svelte plugin options, and this error goes away.

```
export default {
    input: 'src/main.js',
    output: {
        sourcemap: true,
        format: 'iife',
        name: 'app',
        file: 'public/build/bundle.js'
    },
    plugins: [
        svelte({
            emitCss: false,  // <-- ADD THIS LINE
            compilerOptions: {
                // enable run-time checks when not in production
                dev: !production
            }
        }),
```

I'm pretty sure this is a step backwards.  The new template is intended to output a separate "bundle.css" file through rollup.  Setting this "emitCss:false" option prevents that process.  However, it also gets the latest template install to work on Windows.

**Comment by antony** [comment]
Can somebody encountering this do:

`npm install --save-dev rollup-plugin-svelte@6`

and then try again?

I've seen this error (on Linux too) with `rollup-plugin-svelte@7` plugin unless you apply @mattsahr 's fix above.

**Comment by SARFEX** [comment]
> Can somebody encountering this do:
> 
> `npm install --save-dev rollup-plugin-svelte@6`
> 
> and then try again?

Yes it helps.
But with rollup.config.js fix, because:

```
d:\Projects\svelte-app>npm run dev

> svelte-app@1.0.0 dev d:\Projects\svelte-app
> rollup -c -w

rollup v2.34.1
bundles src/main.js → public\build\bundle.js...
[!] (plugin svelte) Error: Unrecognized option 'compilerOptions'
src\App.svelte
Error: Unrecognized option 'compilerOptions'
    at d:\Projects\svelte-app\node_modules\svelte\src\compiler\compile\index.ts:41:10
    at Array.forEach (<anonymous>)
    at validate_options (d:\Projects\svelte-app\node_modules\svelte\src\compiler\compile\index.ts:35:23)
    at compile (d:\Projects\svelte-app\node_modules\svelte\src\compiler\compile\index.ts:76:2)
    at d:\Projects\svelte-app\node_modules\rollup-plugin-svelte\index.js:252:22

```

**Comment by benmccann** [comment]
If you are encountering this issue, please tell us:
* Are you encountering this error right after running `npx degit sveltejs/template svelte-app`?
* If you are encountering it in a project of your own or a project with any changes from the base template, please share the full repo on GitHub that reproduces it

**Comment by kunom** [comment]
Same issue here while trying build the unmodified template. It worked maybe last week, but now not anymore.

**Comment by antony** [comment]
Trying to remember this from memory and type on a phone, so forgive me, but, put this online plugin in your rollup config after 'svelte':

{
  transform (code, id) {
    console.log(id)
    id.endsWith('App.svelte') && console.log(code)
  }
}

Then run the build, does the id for the CSS file match the import name in the printed code?

**Comment by SARFEX** [comment]
> Then run the build, does the id for the CSS file match the import name in the printed code?

![image](https://user-images.githubusercontent.com/801248/101207899-63074000-3682-11eb-934d-ec8098bfd513.png)

**Comment by kunom** [comment]
> Then run the build, does the id for the CSS file match the import name in the printed code?

Do we have an issue when building on a network share (note that one backslash is missing):

```
[...]
id=\\diskstation\kuno\tmp\svelte-app\src\App.svelte
/* \diskstation\kuno\tmp\svelte-app\src\App.svelte generated by Svelte v3.31.0 */
[...]
```

By the way, my CLI is at `T:\tmp\`...

**Comment by kunom** [comment]
It looks so. When doing things on the C: drive, everything works.

**Comment by dimfeld** [comment]
This is a similar another issue about problems with building from other drive letters: https://github.com/sveltejs/svelte/issues/5686. No solution unfortunately, just linking it here for reference. I do note that some of the problems screenshots above from other people appear to show `C:`.

**Comment by mattsahr** [comment]
> I found one solution for this.
> In `rollup.config.js` you can add `emitCss: false` to the svelte plugin options, and this error goes away.

To close the loop for my case: my template install started working again, in the standard out-of-the-box setup (I no longer needs the  `emitCss: false` setting).  For no reason that I can figure out, it "just works" again.  

Not sure how helpful this is, but it's another data point, along the lines of "... did you reboot?"

**Comment by MotusSimon** [comment]
I am experiencing this on a Windows 10 PC with a fresh install of both the tools and template.  I am running off c:.  @mattsahr 's suggested emitCss fix does result in a launched application.  Removing the emitCss again results in the original failed behaviour.

**Comment by lukeed** [comment]
Revisit the README and the CHANGELOG for 7.0.0.

There are breaking changes. You **cannot** simply upgrade versions – things will _intentionally_ break until you make the required changes.

Using `emitCss: false` **is not** a solution. Doing this will inline your CSS inside your JS code, resulting in significantly larger JS output. Deploying to production with this configuration is strongly discouraged & should be considered an anti-pattern.

**Comment by dimfeld** [comment]
If your rollup config is set up correctly and you are still having issues, please try upgrading your `rollup-plugin-css-only` to version 3.1.0. I'm not sure if it will fix every issue that has been reported here, but I think it should fix at least some of them.

**Comment by SARFEX** [comment]
I checked the current version - the problem is solved 🥳
