### ISSUE TITLE
Socket.io doesn't work in latest Svelte Template 

### ISSUE THREAD

**Issue by charlie632** [sveltejs/template#195]
Also posted in: https://github.com/sveltejs/svelte/issues/5725

**Describe the bug**

I don't know if this is the best place to post this, but I created a new Svelte project with

`npx degit sveltejs/template my-proj` and then installed `yarn add socket.io-client`. Then, just by importing `socket.io-client` into my app, I get this error:

```
polling-xhr.js:18 Uncaught ReferenceError: Cannot access 'XMLHttpRequest' before initialization
```

If I remove the `import io from 'socket.io-client'` line, it runs perfectly.

I tried with a vanilla JS project bundled with webpack and I was able to use the library.

Also tried it with a new create-react-app, so I'm thinking it is how rollup is bundling that specific library?

Please, if this is not the correct place to post this let me know and I'll post it again in a different forum.

**Logs**
Please include browser console and server logs around the time this bug occurred.

In the browser console just by having `socket.io-client` imported
```
polling-xhr.js:18 Uncaught ReferenceError: Cannot access 'XMLHttpRequest' before initialization
```

**To Reproduce**
To help us help you, if you've found a bug please consider the following:

* If you can demonstrate the bug using https://svelte.dev/repl, please do.
* If that's not possible, we recommend creating a small repo that illustrates the problem.
* Reproductions should be small, self-contained, correct examples – http://sscce.org.

```
npx degit sveltejs/template proj
cd proj
yarn install
yarn add socket.io-client
# 	import io from 'socket.io-client' inside App.svelte
yarn dev
```

Bundling looks good, but the app breaks at runtime

**Expected behavior**

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  Stack trace goes here...
</details>

**Information about your Svelte project:**
To make your life easier, just run `npx envinfo --system --npmPackages svelte,rollup,webpack --binaries --browsers` and paste the output here.

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 61.45 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.3/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 84.1.12.114
    Chrome: 86.0.4240.198
    Chrome Canary: 89.0.4337.0
    Firefox Developer Edition: 84.0
    Safari: 14.0
  npmPackages:
    rollup: ^2.3.4 => 2.33.3
    svelte: ^3.0.0 => 3.30.0

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Svelte entirely?

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by antony** [comment]
You should install all dependencies as dev dependencies - please check you're doing that first.

I don't think this is a bug with the Svelte template, more the way rollup is bundling the dependencies, so it might be better not raised as an issue, but discussed in the Svelte discord.

**Comment by Conduitry** [comment]
Yes, your dependencies need to be installed as dev dependencies for the default Rollup config to bundle them. And this is indeed a support question, better suited for the Discord server.
