### ISSUE TITLE
Optional dependency warning - fsevents

### ISSUE THREAD

**Issue by markfirmware** [sveltejs/template#196]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/rollup/node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

If the dependency is optional, can it be coded to not produce this warning?

**Comment by Conduitry** [comment]
This is an optional dependency of Rollup's, not this template's. But no, there's not a reasonable way for them to avoid that warning as far as I know.

**Comment by markfirmware** [comment]
Thank you for the quick service! I think it is sloppy enough to pursue over at rollup. Thanks!
