### ISSUE TITLE
SPA

### ISSUE THREAD

**Issue by schlumpfling42** [sveltejs/template#219]
The readme explains how to start the server as SPA, but this way it doesn't watch files.
How can I set SPA up to run in dev?

**Comment by Conduitry** [comment]
`npm run dev` calls `npm run start` internally, so adding `--single` to `npm run start` will make `npm run dev` also run in SPA mode.

**Comment by schlumpfling42** [comment]
Hmmm ... it doesn't do that for me. I set up the project a few days ago, where there changes since then?
