### ISSUE TITLE
Issues using uuid and nanoid package - crypto problem?

### ISSUE THREAD

**Issue by student020341** [sveltejs/template#221]
[This](https://github.com/sveltejs/svelte/issues/2848) seems to still be an issue in 2021, at least without some unobvious configuring. I created an instance of sveltejs/template with npx degit and got the exact same error from both the uuid library and nanoid library: 

```
main.ts:5 Uncaught ReferenceError: crypto$1 is not defined
```

There is also no stack trace to see. It has 1 line, `(anonymous) @ main.ts:5` which is pointing at the closing brace of new App(...);

I think this is the relevant section of my rollup config?
```
resolve({
			browser: true,
			dedupe: ['svelte']
		}),
```

I hope I'm missing something simple, I'm trying to get uuids working on the client for some temporary unique ids. I will try the standalone uuid-v4 library as the suggested workaround for the linked issue, but its last publish was 8 years ago and I suspect the more popular uuid package or nanoid probably have some improvements I would benefit from.

The error happens just by importing either library:
```
import {nanoid} from "nanoid"; 
// or
import {v4} from "uuid";
```

Edit to include my rollup config. It's mostly untouched, I just have some aliases for different paths in the src folder.

```
import svelte from 'rollup-plugin-svelte';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import sveltePreprocess from 'svelte-preprocess';
import typescript from '@rollup/plugin-typescript';
import css from 'rollup-plugin-css-only';
import {config} from "dotenv";
import replace from "@rollup/plugin-replace";
import alias from "@rollup/plugin-alias";
import path from "path";
import copy from "rollup-plugin-copy";

const production = !process.env.ROLLUP_WATCH;

function serve() {
	let server;

	function toExit() {
		if (server) server.kill(0);
	}

	return {
		writeBundle() {
			if (server) return;
			server = require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
				stdio: ['ignore', 'inherit', 'inherit'],
				shell: true
			});

			process.on('SIGTERM', toExit);
			process.on('exit', toExit);
		}
	};
}

export default {
	input: 'src/main.ts',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		copy({
			targets: [
				{src: "node_modules/jsoneditor/dist/img", dest: "public/build"}
			]
		}),
		replace({
			process: JSON.stringify({
				env: {
					isProd: production,
					...config().parsed
				}
			})
		}),
		alias({
			resolve: [".svelte", ".js", ".ts"],
			entries: [
				{
					find: "@stores",
					replacement: path.resolve(__dirname, "src/stores")
				},
				{
					find: "@routes",
					replacement: path.resolve(__dirname, "src/routes")
				},
				{
					find: "@controllers",
					replacement: path.resolve(__dirname, "src/controllers")
				},
				{
					find: "@components",
					replacement: path.resolve(__dirname, "src/components")
				}
			]
		}),
		svelte({
			preprocess: sveltePreprocess({ sourceMap: !production }),
			compilerOptions: {
				// enable run-time checks when not in production
				dev: !production
			}
		}),
		// we'll extract any component CSS out into
		// a separate file - better for performance
		css({ output: 'bundle.css' }),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration -
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
		commonjs(),
		typescript({
			sourceMap: !production,
			inlineSources: !production,
			rootDir: "./src"
		}),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};

```

**Comment by student020341** [comment]
I created yet another instance of the template with npx degit and without running the typescript upgrade script and without creating those shortcuts in a brand new project, the issue does not happen. 

I don't know what's up with the configs I posted, but I guess I can live without them and transplant most of the code into a new project. It would be great to know what's wrong with them, though. No doubt the new project configs will slowly transform into those over time.

**Comment by lukeed** [comment]
Probably related to #200, or could be your `tsconfig.json` missing the `esModuleInterop` option.

See if the same issue happens with [`uid`](https://github.com/lukeed/uid) and/or [`lukeed/uuid`](https://github.com/lukeed/uuid). Both of those are configured correctly and use named imports, which removes the need for `esModuleInterop` and/or `allowSyntheticDefaultImports`

**Comment by antony** [comment]
I believe that nanoid has a specific way of importing in a browser environment specifically to avoid the crypto problem.

**Comment by student020341** [comment]
@antony I wonder if the uuid library has something similar since it had an identical 'crypyo' related error. I thought it was browser:true in the rollup resolve, but that didn't fix it for me.

@lukeed  I inspected the source on that error and came to the conclusion described in the answers there, I had an issue like that "process undefined" when I made a new svelte project to isolate & reproduce this issue. It was resolved by having process.env created with the replace rollup plugin. 

I don't see the interop option you described so maybe that's it. Maybe that's why I see other issues like these when I convert my project to typescript yet can't reproduce issues in a fresh template. Here's my tsconfig:

```
{
  "extends": "@tsconfig/svelte/tsconfig.json",

  "include": ["src/**/*"],
  "exclude": ["node_modules/*", "__sapper__/*", "public/*"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@routes/*": ["./src/routes/*"],
      "@stores/*": ["./src/stores/*"],
      "@controllers/*": ["./src/controllers/*"],
      "@components/*": ["./src/components/*"]
    },
    "types": ["node"]
  }
}
```

Also, yes, your properly configured modules do work without issue! Would you mind letting me know what/how that interop option works? I suspect that might be at the root of several issues I've had.

**Comment by lukeed** [comment]
Both options listed are `compilerOptions` inside `tsconfig`. You have to add them. They're both related to `import foo from 'foo'`-type statements, and tell TypeScript to add extra code to check for (effectively) `module.exports` vs `exports.default` code.

There are no configuration changes inside my modules that allowed them to work (in this case). By offering _named_ exports, you skip the need for interop because there's just no guesswork to be had around `default` imports.

**Comment by student020341** [comment]
I googled around and tried that, I did put that into my compiler options so that chunk of the config now looks like this:
```
"compilerOptions": {
    "esModuleInterop": true,
    "baseUrl": ".",
    "paths": {
      "@routes/*": ["./src/routes/*"],
      "@stores/*": ["./src/stores/*"],
      "@controllers/*": ["./src/controllers/*"],
      "@components/*": ["./src/components/*"]
    },
    "types": ["node"]
  }
```

but no luck, still have the same error in the console just by importing {v4} from the uuid. When I try using secure from your package, it gives me an error like this:
```
Uncaught TypeError: crypto.randomBytes is not a function
    at random (index.mjs:4)
    at v4 (index.mjs:11)
    at instance$c (EditCalculations.svelte:11)
    at init (index.mjs:1471)
    at new EditCalculations (EditCalculations.svelte:32)
    at Array.create_default_slot_1 (App.svelte:23)
    at create_slot (index.mjs:61)
    at Array.create_else_block (Route.svelte:41)
    at create_if_block (Route.svelte:41)
    at Object.update [as p] (Route.svelte:40)
```

Maybe that's a hint at the issue? Or is secure only for node/server environments? I suspect we're getting closer with this being a typescript problem since that explains fresh projects not having the issues I run into. So, in any case, thanks and at least my short terms are resolved by your uuid package.

**Comment by lukeed** [comment]
Somehow you're loading Node.js code. I know this is happening because you're hitting [this file](https://github.com/lukeed/csprng/blob/master/src/node.js).

Maybe try moving the `copy`, `replace`, and `alias` plugins to the end of the pluigns list, or disabling them for now? Plugin order can make a difference.

---

If you want to silence the error (at least with `uuid/secure`) you can enable [this](https://www.npmjs.com/package/@rollup/plugin-node-resolve#user-content-preferbuiltins), but that's not actually a solution. You don't want Node.js code running (or trying to run) inside the browser.

**Comment by lukeed** [comment]
Oh wait, this is `rollup-plugin-svelte`'s doing! https://github.com/sveltejs/rollup-plugin-svelte/blob/master/index.js#L67

**Comment by student020341** [comment]
Moving those plugins to the end did not seem to resolve the issue. I am also pretty sure removing replace will cause many of the libraries checking for process.env (like nanoid) to throw errors. I ran into that will creating a new instance of the template, I had to add the replace plugin to get it working. I think that might also serve as evidence that replace is not the culprit. 

Removing alias is going to break all of my imports, so I'll try recreating those parts of this project in a fresh project to see if any of them are the problem. I don't know if that'll get us closer to an answer but it might give us an inconclusive suggestion that typescript is the problem :)

**Comment by lukeed** [comment]
What version of `@rollup/plugin-node-resolve` are you using?

**Comment by student020341** [comment]
Interesting - in the fresh project without plugins, I can load nanoid and your uuid package, but still not the secure one. Even more interesting - it throws the previous error just from importing it:
```
Uncaught ReferenceError: crypto$1 is not defined
```
And that is a fresh, non typescript project!

Here's the rollup.config.js for that:
```
import svelte from 'rollup-plugin-svelte';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import css from 'rollup-plugin-css-only';
import replace from "@rollup/plugin-replace";
import {config} from "dotenv";

const production = !process.env.ROLLUP_WATCH;

function serve() {
	let server;

	function toExit() {
		if (server) server.kill(0);
	}

	return {
		writeBundle() {
			if (server) return;
			server = require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
				stdio: ['ignore', 'inherit', 'inherit'],
				shell: true
			});

			process.on('SIGTERM', toExit);
			process.on('exit', toExit);
		}
	};
}

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		svelte({
			compilerOptions: {
				// enable run-time checks when not in production
				dev: !production
			}
		}),
		// we'll extract any component CSS out into
		// a separate file - better for performance
		css({ output: 'bundle.css' }),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration -
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
		commonjs(),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser(),
		replace({
			process: JSON.stringify({
				env: {
					isProd: production,
					...config().parsed
				}
			})
		}),
	],
	watch: {
		clearScreen: false
	}
};
```
I see your new comment - I experienced this issue with whatever the template stock version is and see the same issue after using ncu to upgrade the packages. Here is the updated package.json:
```
{
  "name": "svelte-app",
  "version": "1.0.0",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.1.0",
    "@rollup/plugin-node-resolve": "^11.2.0",
    "@rollup/plugin-replace": "^2.3.4",
    "dotenv": "^8.2.0",
    "nanoid": "^3.1.20",
    "rollup": "^2.39.0",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.1.0",
    "rollup-plugin-terser": "^7.0.2",
    "svelte": "^3.32.3"
  },
  "dependencies": {
    "@lukeed/uuid": "^2.0.0",
    "sirv-cli": "^1.0.11"
  }
}

```

**Comment by lukeed** [comment]
Yeah, my current thought is that `@rollup/plugin-node-resolve` isn't handling nested dependencies' `exports` correctly. The `crypto` parts are _only_ included when `lukeed/uuid/secure` is in use – that submodule pulls in `lukeed/csprng` which has [this `package.json` file](https://github.com/lukeed/csprng/blob/master/package.json).

We can see that this module, by default, points to Node.js entries by default. However, there are `browser` and `exports[*].browser` fields which are not getting picked up.

None of this really helps you right now, but I think we've landed on the issue... although I can't speak to how `nanoid`/`uuid` are set up. I'm assuming it's a similar thing if you still have issues beyond the `esModuleInterop` and `allowSyntheticDefaultImports` additions.

**Comment by lukeed** [comment]
Yup, here's an existing issue: https://github.com/rollup/plugins/issues/781

**Comment by student020341** [comment]
I'm realizing I posted to this repo accidentally instead of svelte, but I'm glad to have found answers either way! 

> None of this really helps you right now, but I think we've landed on the issue

The ids I need are temporary front end related ids that are nested under another object that has an _id from mongo. The ids are something to give to svelte so the local variables don't get confused when I move the objects that will have these temporary ids around. I think your "non secure" uuid package will work fine for my current / short term needs. I can even spare the effort of migrating to a new project thanks to that package, so thank you. 

At least users who arrive here by searching for a uuid solution will have something that works until that larger issue you referenced is resolved. Should I close this issue since there is one open on the (probably) relevant repo?

**Comment by lukeed** [comment]
You actually posted it to svelte, but we transferred it here.

I'd suggest a workaround/satisfactory compromise for the time being. You can post that here as a follow-up if you'd like.

But because this isn't an issue with anything inside the svelte-side of things (the template, the plugin, or the compiler itself) I'm going to go ahead and close this & try to make progress on the linked Rollup issue.

Thanks!
