### ISSUE TITLE
TS: error: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'. ts(1343)

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/template#227]
Right after the script for typescript if I try to use:

```js
`${import.meta.env.SOME_ENV}`
```

I'm getting this error:

`The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'. ts(1343)`.

Why?

How can we fix this?

**Comment by lukeed** [comment]
The TS error hints at the answer:

Add `"module": "es2020"` to the `compilerOptions` in your `tsconfig.json` file

**Comment by frederikhors** [comment]
Can we put it in the script too? Why not?

**Comment by lukeed** [comment]
The template is set up to output an `iife` bundle. Telling TS to allow `import.meta.*` will allow for the output to contain invalid syntax, as only `<script type="module">`s can accept ESM syntax features.

**Comment by frederikhors** [comment]
Can you please recommend a way to whoever comes here to solve the problem?

**Comment by frederikhors** [comment]
Cause the template is also used for esm projects.

**Comment by lukeed** [comment]
It's the same as the above?

Then you need to use `<script type="module">` in your `index.html` file, as mentioned.
And you need to change the `output.format` in your `rollup.config.js` from `iife` to `esm`.

**Comment by frederikhors** [comment]
The problem here is it cannot find `import.meta` types.

See here: https://github.com/snowpackjs/snowpack/discussions/1433#discussioncomment-267428. Snowpack is using this to fix this error: `"types": ["svelte", "@types/snowpack-env"]` in `tsconfig.json`.

Why we not?

**Comment by frederikhors** [comment]
I found a way now: copy https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/snowpack-env/index.d.ts.

**Comment by lukeed** [comment]
`import.meta.env` is specific to Snowpack. 

If you used `import.meta.url`, for example, you don't need an additional `types` package/entry since it's a native built-in.

**Comment by frederikhors** [comment]
Oh wow. My head is burning.

I was using in my old project with this template `process.env` with `@rollup/plugin-replace` and .dotenv.

Eslint-typescript is complaining about this too now:

`Unsafe member access .env on an any value.eslint@typescript-eslint/no-unsafe-member-access`.

for

```js
if (process.env.NODE_ENV === 'production') {
```

How can I fix this?

**Comment by lukeed** [comment]
This is a separate issue & I don't want this to become a rabbit hole – I advise you go to discord with this.

But, it's effectively telling you "process.env" is "unsafe" because `process` may not be defined in runtime... which is correct since the browser does not have a `process` global. You've corrected this by using `plugin-replace` to ensure it's not left in the output, but your TS isn't aware of this. I would just turn off that eslint rule.

Hope that helps~! Closing.
