### ISSUE TITLE
Dotaz - odhlášení konzultanta při "nečinnosti"?

### ISSUE THREAD

**Issue by jitkamedricka** [sveltejs/template#230]
Chtěla jsem se na popud našeho IT zeptat, jak je to teď ošetřeno, pokud by pracovník zůstal někde delší dobu přihlášen (spíše myšleno omylem - změnil by připojení, zapomněl se vypnout po službě apod.). Je to nějak nastaveno? Například, že by po určité době "nečinnosti" byl požádán o potvrzení, zda je připojen, a pokud by k potvrzení nedošlo, byl by odpojen? Jde také o to, aby se například pracovník s koncem provozní doby nezapomněl odhlásit a klientům by se tak stále zobrazovala možnost přihlášení  a čekali by na spojení i mimo provozní dobu...

**Comment by Conduitry** [comment]
Please post issues only in English, and please don't ask support questions.

From Google Translate, it sounds like this is asking about timing out sessions that are idle, which is something that would be up to your app, and has nothing to do with Svelte.

**Comment by jitkamedricka** [comment]
sorry, it was a mistake. I sent it on another place.
