### ISSUE TITLE
A question about "sirv".

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/template#25]
I know I'm not following the rules of common sense by opening an issue that I might not open.

But I believe that a wonderful project like svelte requires good tools.

`sirv` is at a very early stage and cannot compete with tools like` browsersync` or others already mentioned here (https://github.com/sveltejs/template/issues/8) and here (https://github.com/sveltejs/template/issues/17).

Please understand our complaints as daily developers.

Thank you.

**Comment by EmilTholin** [comment]
I don't think there is any reason to remove `sirv`. It works great together with LiveReload.

**Comment by frederikhors** [comment]
Can you show an example please?

**Comment by EmilTholin** [comment]
You can try [this repository on this branch](https://github.com/EmilTholin/template/tree/rollup-plugin-livereload), run `npm install && npm run dev`, visit `http://localhost:5000`, and do a change to the `src/App.svelte` file to see how the browser reloads automatically.

**Comment by frederikhors** [comment]
Fine, great. I think we can go with this.

Just one thing: if I edit rollup config file it crashes.

Is it a problem? I don't think so.

**Comment by EmilTholin** [comment]
> Fine, great. I think we can go with this.

Great!
> Just one thing: if I edit rollup config file it crashes.

It does that even without the LiveReload plugin, so I don't think that's related to that change. Just like you, I don't think that's a problem.
