### ISSUE TITLE
Upgrade packages

### ISSUE THREAD

**Issue by bfg-lazaro** [sveltejs/template#259]
A simple question.
Is it advisable to update all packages of template?
I find that for example svelte has version 3.0.0 and I don't understand why it has not been updated to the latest .

I have updated everything to the latest version using npm-check-updates and everything seems to work fine.
I'm lost  🤷‍♂️

**Comment by Conduitry** [comment]
Svelte is at version `^3.0.0`, not `3.0.0`. `^3.0.0` which will resolve to the latest `3.x.x` version available at a given time. https://docs.npmjs.com/about-semantic-versioning
