### ISSUE TITLE
Add parcel template please

### ISSUE THREAD

**Issue by shashkovdanil** [sveltejs/template#26]

**Comment by Conduitry** [comment]
The [Svelte Parcel plugin](https://github.com/DeMoorJasper/parcel-plugin-svelte) is community-maintained, and we don't want to be maintaining an official template for it. It looks like the plugin's repo has an example starter project [https://github.com/DeMoorJasper/parcel-plugin-svelte/tree/master/svelte-3/svelte-3-example](here).

**Comment by shashkovdanil** [comment]
@Conduitry, wow, thank you!
