### ISSUE TITLE
`npm run dev` updates terminal quickly and repeatively when nothing is going

### ISSUE THREAD

**Issue by lilydjwg** [sveltejs/template#260]
When I run `npm run dev`, the terminal shows

```
⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠧ : timing npm:load Completed in 17ms
> svelte-app@1.0.0 start
> sirv public --no-clear "--dev"

⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠧ : timing npm:load Completed in 18ms
  Your application is ready~! 🚀

  - Local:      http://localhost:5000
  - Network:    Add `--host` to expose

────────────────── LOGS ──────────────────

⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠧ : timing npm:load Completed in 17ms
```

And the last line keeps updating dozens of time every second, spinning up my CPU fan. The number keeps changing between two values.

I don't know what goes wrong. I just `use`d this template repository, ran an `npm install` before `npm run dev`.

```
>>> node --version
v16.10.0
>>> npm --version
7.24.1
```

I'm on Arch Linux.

**Comment by Conduitry** [comment]
These are coming from npm. https://docs.npmjs.com/cli/v7/using-npm/config#loglevel You must have the loglevel configured at something other than the default.

**Comment by lilydjwg** [comment]
Oh thanks! Yes, I have set npm logging level to info in the past so that I know it's doing its job when `npm install`. Disabling the info logging, it no longer uses quite a bit CPU.
