### ISSUE TITLE
tsconfig error when cloning

### ISSUE THREAD

**Issue by Specy** [sveltejs/template#261]
I just followed the guide at [svelte](https://svelte.dev/blog/the-easiest-way-to-get-started) but after cloning, running the typescript conversion script and installing modules, i get an error in the tsconfig.json file saying:
```
Path to base configuration file to inherit from. Requires TypeScript version 2.1 or later.
```

**Comment by Mlocik97** [comment]
There is workaround for it, when copying content of `./node_modules/@tsconfig/svelte/tsconfig.json` to `./tsconfig.json`, and removing `"extends": "@tsconfig/svelte/tsconfig.json"` (keeping include and exclude). When problem will be fixed, You can change `./tsconfig.json` back to it's default version

**Comment by Specy** [comment]
Ok thanks, never seen vite before but I guess I'll search for that
