### ISSUE TITLE
could not find commit hash for HEAD

### ISSUE THREAD

**Issue by HBartolin** [sveltejs/template#266]
>npx degit sveltejs/template my-svelte-project
npx: installed 1 in 19.27s
! could not fetch remote https://github.com/sveltejs/template
! could not find commit hash for HEAD

>npm --version
6.14.13

>npx` --version
6.14.13

**Comment by Conduitry** [comment]
See #70 / #240 / https://github.com/Rich-Harris/degit/issues/37 - This error generally means you don't have Git installed.
