### ISSUE TITLE
I have to save everytime after making changes

### ISSUE THREAD

**Issue by chidam333** [sveltejs/template#279]
![image](https://user-images.githubusercontent.com/86545749/148228422-4b0abe4c-4052-48ca-a822-bd21866e8ea6.png)
- I am using VS code and WINDOW's machine
- The file doesn't save itself i have manually ctrl-s all time  
- The following white dot appears when I make changes in a file 
![image](https://user-images.githubusercontent.com/86545749/148228637-0ccbfb41-f721-41ea-ada5-9ee37c3f749a.png)
- I have used this same template before never faced this issues (still I am a beginner)

**Comment by Conduitry** [comment]
Whether the editor automatically saves is a configuration of the editor and is not something controlled by this template. If it worked before, you presumably had autosave enabled at the time.
