### ISSUE TITLE
Rollup watch issue

### ISSUE THREAD

**Issue by unlocomqx** [sveltejs/template#29]
Watch only works once, after that, changes aren't detected
This solved the issue for me
https://github.com/rollup/rollup/issues/1666#issuecomment-372383550

Please include it in the template if possible

**Comment by frederikhors** [comment]
No problem for me on Windows.

Can you write npm versions, package.json, OS?

**Comment by unlocomqx** [comment]
Here's the info
node v11.14.0
npm 6.9.0
Linux Mint 19 - 4.15.0-48-generic #51-Ubuntu SMP
package.json
```
{
  "name": "svelte-app",
  "version": "1.0.0",
  "devDependencies": {
    "npm-run-all": "^4.1.5",
    "rollup": "^1.10.1",
    "rollup-plugin-commonjs": "^9.3.4",
    "rollup-plugin-livereload": "^1.0.0",
    "rollup-plugin-node-resolve": "^4.2.3",
    "rollup-plugin-svelte": "^5.0.3",
    "rollup-plugin-terser": "^4.0.4",
    "sirv-cli": "^0.4.0",
    "svelte": "^3.0.0"
  },
  "scripts": {
    "build": "rollup -c",
    "autobuild": "rollup -c -w",
    "dev": "run-p start:dev autobuild",
    "start": "sirv public",
    "start:dev": "sirv public --dev"
  }
}
```

**Comment by frederikhors** [comment]
Linux is the problem.

Windows no problem at all.

Maybe @EmilTholin can help here.

**Comment by unlocomqx** [comment]
It's alright, I wanted to raise the issue partly so other people find it when they encounter the same problem as I did
Cheers

**Comment by tobias-kuendig** [comment]
I'm having the same problem. If I change `livereload('public')` to `livereload('src')` it works but I'm always seeing the previous version (it's always one "save" behind).

I am also on Linux.

**Comment by unlocomqx** [comment]
I'll close this issue for now
