### ISSUE TITLE
FYI: fix for failing auto rebuild  on Windows

### ISSUE THREAD

**Issue by seriousme** [sveltejs/template#3]
Hi,

I  followed the instructions from the [guide](https://svelte.technology/guide)  to install the template.
Installation went smooth and after `npm run dev` I got the "serving" message. However going to `localhost:5000` got me a blank screen.

Looking at `package.json` in the template `npm run dev` does: 
`"dev": "serve public & rollup -c -w"`
which works great on Linux and Mac , but not on Windows.

The solution is quite simple:
- add ` "npm-run-all` to the `devDependencies`
- change the `scripts` section into:
```json
"scripts": {
    "build": "rollup -c",
    "autobuild": "rollup -c -w",
    "dev": "run-p start autobuild",
    "start": "serve public"
  }
```
This way the scripts are not depending on OS-specific features.

Cheers,
Hans

**Comment by EmilTholin** [comment]
This issue can be closed.
