### ISSUE TITLE
Clean package.json script.

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/template#32]
I will make a PR soon for this.

Clean package.json script.

**Comment by Conduitry** [comment]
What was this issue for?

**Comment by frederikhors** [comment]
To add something like the below in `package.json`:

```json
  "scripts": {
    ...
    "clean": "rm -rf dist/* tmp/*",
    ...
  }
```

But this is just good if we gonna use a `dist` path for building copy from `public/*` (https://github.com/sveltejs/template/pull/38).

What do you thing about?

**Comment by pngwn** [comment]
This would not work in windows.

**Comment by frederikhors** [comment]
I know, we can use `rimraf` https://github.com/isaacs/rimraf.

**Comment by Conduitry** [comment]
#38 has been rejected, so I don't see a particular need for this. Closing.
