### ISSUE TITLE
What does "window.app = app;" mean?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/template#36]
The content of `main.js` in `github.com/sveltejs/template-webpack`:

```js
import App from './App.svelte';

const app = new App({
	target: document.body,
	props: {
		name: 'world'
	}
});

window.app = app;

export default app;
```

The same file in `github.com/sveltejs/template`:

```js
import App from './App.svelte';

const app = new App({
	target: document.body,
	props: {
		name: 'world'
	}
});

export default app;
```

I'm wondering what difference `window.app = app;` means.

Can you answer please?

**Comment by Conduitry** [comment]
`window.app = app` stores a copy of the app instance as a global variable on `window`. Top-level `let`s and `const`s in ES modules (or in strict mode) do not normally produce global variables the way `var`s at the top level would in ES5. This just lets you interact with the global `app` from anywhere or from in the browser devtools console.
