### ISSUE TITLE
Move index.html and global.css to /src

### ISSUE THREAD

**Issue by blindfish3** [sveltejs/template#4]
Just a suggestion; but it would be more helpful to have index.html and global.css in the /src folder and copied to /public on build.
I made the mistake of copying everything in a test project except /node_modules and /public expecting to be able to rebuild from there; and then realised that I had no index.html.  Others might add a clean process to their build pipeline and wipe those files out that way...

**Comment by frederikhors** [comment]
I agree. I will make a PR soon.

**Comment by frederikhors** [comment]
@blindfish3, do you like https://github.com/sveltejs/template/pull/38?

**Comment by akauppi** [comment]
@Rich-Harris has done a change 27 days ago regarding #38 :

>Thank you — I think it's probably easier to keep public as is, but move the generated files to an ignored public/build folder, so I've done that

I think this was a good move. Now, can we close this issue?

**Comment by frederikhors** [comment]
I agree with @blindfish3 here.

I prefer a separate folder.

Please reconsider it.

**Comment by Conduitry** [comment]
We want as little going on in the default template as possible - and copying a file as-is from `src` to `public` is unnecessary. #38 has been closed, so closing this as well.
