### ISSUE TITLE
Default clearScreen to false

### ISSUE THREAD

**Issue by anonimusprogramus** [sveltejs/template#40]
**Expected Behavior:**

Running` npm run dev` should make both Sirv and Rollup **output some infos to screen**.

**Actual Behavior:**

As soon as Sirv output infos, **Rollup's infos covering it**.

**Proposal:**

Please add `watch: { clearScreen: false }` as default in **rollup.config.js**, so new user can see what port Svelte's running.

I also have submitted [this issue in Rollup repo](https://github.com/rollup/rollup/issues/2820).

**Comment by lukeed** [comment]
Solved via 36940222be6c2fcb983da62c8eb4d235be2081cf 🎉
