### ISSUE TITLE
Example of babel integration

### ISSUE THREAD

**Issue by bgreater** [sveltejs/template#41]
Can we get an example of how to use babel with the svelte template? 

Try as I may, I can't get transforms to work correctly on all the bundle code and polyfills are none existent as well.  I'm sure it's some configuration issue, but having an example to work from would be great for the community.

**Comment by ArrowBaZ** [comment]
Hello @bgreater ,
You can find a example here: https://github.com/jimutt/svelte-pick-a-place/blob/master/rollup.config.js

**Comment by eclectic-coding** [comment]
Another option would be to use [Parceljs](https://parceljs.org/). It is almost a zero configuration bundler. Look at this [article](https://dev.to/alexparra/basic-svelte-app-with-parcel-30i5) to explain the simple setup.
parcel really has become my bundler of choice.

**Comment by antony** [comment]
@bgreater if it's useful - here's how I do it in Sapper https://github.com/antony/sapper-ie

**Comment by sw-yx** [comment]
so i see how u guys apply it with the rollup plugin, but i think for new syntax you need to use preprocessors. example:

```html
<script>
  class Cow {
	// stage 3 class properties syntax
	static sound = "moo";
  }
</script>


<main>
  <h1>Cow says {Cow.sound}!</h1>
</main>
```

now we need to transpile what's in the script, otherwise acorn throws a fit:

```bash
[!] (plugin svelte) ParseError: Unexpected token
src/App.svelte
3:   class Cow {
4:     static sound = "moo";
             ^
5:   }
6: </script>
ParseError: Unexpected token
    at error (/Users/swyx/Desktop/Work/testbed/trybabelrecipe/svelte-app/node_modules/svelte/src/compiler/utils/error.ts:25:16)
    at Parser$1.error (/Users/swyx/Desktop/Work/testbed/trybabelrecipe/svelte-app/node_modules/svelte/src/compiler/parse/index.ts:96:3)
    at Parser$1.acorn_error (/Users/swyx/Desktop/Work/testbed/trybabelrecipe/svelte-app/node_modules/svelte/src/compiler/parse/index.ts:89:8)
```

So the fix is somewhat different. Make sure @babel/core and the rest of your plugins/presets are installed, then:

```js
// rollup.config.js
// ...

export default {
	// ...
  plugins: [
    svelte({
      // ...
      preprocess: {
        script: ({ content }) => {
          return require("@babel/core").transform(content, {
            plugins: ["@babel/plugin-proposal-class-properties"],
          });
        },
      },
    }),
 // ...
```
