### ISSUE TITLE
sirv-cli in dependencies

### ISSUE THREAD

**Issue by khullah** [sveltejs/template#44]
I recently had trouble deploying a svelte app to heroku. Sirv wouldn't run. Got me some time until the solution came: the dependency is under "devDependencies" and not "dependencies" in package.json. Heroku strip out those packages after build and server will crash.

Of course sirv is great for development scenarios where things are simple and straightforward, but nonetheless I feel like the template could just be production-ready. As the app scales packages will be added/changed anyway.

**Comment by lukeed** [comment]
Agree with this – turns out to be quite a common case.

Worse case scenario, `sirv-cli` is just installed but never invoked
