### ISSUE TITLE
cannot access by ip, but localhost is access OK!

### ISSUE THREAD

**Issue by qqke** [sveltejs/template#45]
cannot access by ip http://1XX.XX.XX.XX:5000/, but http://localhost:5000/ is access OK!

**Comment by lukeed** [comment]
This was fixed in [`sirv-cli@0.4.4`](https://github.com/lukeed/sirv/releases/tag/v0.4.4). Try again after updating & report back please :)

**Comment by qqke** [comment]
thank you
