### ISSUE TITLE
ValidationError: Home component is not defined

### ISSUE THREAD

**Issue by adonespitogo** [sveltejs/template#5]
Error: [!] (svelte plugin) ValidationError: Home component is not defined

Project structure:

```
src
 - App.html
 - Home.html
 - main.js
```

```html
App.html

<h1>Hello {name}!</h1>
<Home></Home>
```

```html
Home.html
<h2>Home</h2>
```

```javascript
main.js

import App from './App.html';
import Home from './Home.html';

const app = new App({
  target: document.body,
  data: {
    name: 'world'
  },
  components: {Home}
});
export default app;
```
I'm still trying to read the generated js files to see what I'm doing wrong. Will update soon as I made any progress.

**Comment by Conduitry** [comment]
`components` isn't an option passed to a component constructor - it's an option in the behavior `<script>` block in the component that needs to use another component. See https://svelte.technology/guide#nested-components

In your case, you'd want something like

```html
<script>
  import Home from './Home.html';
  export default {
    components: { Home }
  };
</script>
```

in your `App.html`.
