### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by flihub** [sveltejs/template#50]
just tried to svelte, downladed this template and get error ->

![Capture](https://user-images.githubusercontent.com/16720735/60051149-06f16b80-96db-11e9-8c1a-e77fe45af7cb.PNG)

and package json have old versions why no one update this?

**Comment by bravebox** [comment]
I have the same issue.

Windows / Node version v10.7.0

**Comment by lukeed** [comment]
Cannot reproduce with clean `template` clone:

```
git clone git@github.com:sveltejs/template.git svelte-template
cd svelte-template
yarn
yarn build
yarn start
//=> No errors on localhost:5000

rm -rf public
git reset --hard
yarn dev
//=> No errors on localhost:5000
```

Please provide steps if it's possible to see with the base template.

**Comment by frederikhors** [comment]
It works good to me on Windows.

**Comment by flihub** [comment]
tried again same error and bundle.js contains html code build not happend maybe someone suggest something.

node -v : v10.16.0 -- tried previous builds same error

![Capture](https://user-images.githubusercontent.com/16720735/60128903-75e2c900-979c-11e9-8e96-5db989cf64a3.PNG)

**Comment by Conduitry** [comment]
Are there any errors in your terminal? Does `public` actually contain a `bundle.js`? What happens when you run `npm run build`?

**Comment by flihub** [comment]
i tried always npm run start before upside errors.

build/autobuild/dev  = worked // no errors

i found that **sirv** not working after start and start:dev command localhost:5000 opened but not working.

after npm run dev open my svelte public url build success, livereload working

![Capture](https://user-images.githubusercontent.com/16720735/60130372-c576c400-979f-11e9-8b32-ac3f4af7b637.PNG)

**Comment by lukeed** [comment]
You can't `start` without running `build` first.

You are seeing HTML inside your `bundle.js` because:

1) the `bundle.js` _hasn't been built yet_; and 
2) the `sirv` command is run with `--single` flag, which redirects all 404/missing files to `index.html`

This is why you see the `public/index.html` contents.

The `dev` command works for you because it starts the server _and builds the files_ at the same time for you.

**Comment by flihub** [comment]
thx.
