### ISSUE TITLE
Rollup doesn't know changes of any *.svelte in child directory in src

### ISSUE THREAD

**Issue by threeid** [sveltejs/template#53]
Issue (MacOS 10.14.5):
If you have App.svelte in `/src/` and Tab.svelte, TabItem.svelte in `/src/components/`,
 App `import` Tab, Tab `import` TabItem, 
Rollup doesn't know changes in TabItem, but it knows changes in Tab.

Solution:
```javascript
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			include: 'src/**/*.svelte', // add this
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: css => {
				css.write('public/bundle.css');
			}
		}),
```

**Comment by JanTvrdik** [comment]
I have the same problem, but your solution does not seem to work for me (I get "Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)")

**Comment by threeid** [comment]
Hey man, 
Since the template use https://github.com/rollup/rollup-plugin-svelte,
you can check the config here.
