### ISSUE TITLE
Buble and Uglify interplay

### ISSUE THREAD

**Issue by alecglassford** [sveltejs/template#6]
Hi!

I've long used this template without issue, but I recently updated `rollup-plugin-uglify` to version 4 (which removed support for anything beyond ES5) in a project, and I found that it couldn't actually process the output of buble, which emits this object shorthand: 

```
var proto = {
	destroy,
	get,
	fire,
	on,
	set,
	_recompute: noop,
	_set,
	_mount,
	_differs
};
```

Removing the `exclude: 'node_modules/**' ` from the `rollup-plugin-buble` config fixed this for me. (I'm guessing this exclusion was more appropriate before Svelte 2 stopped emitting ES5 code.)

The current configuration of this template actually does seem to produce working ES5 code (haven't actually tested on IE or anything...), because when you use the Uglify that works with post ES5 code, it actually happens to remove the object shorthand. 🤷🏻‍♂️

Which is all to say, everything in the template is fine at the moment as far as ES5 support goes, but this might be something to look out for if you update dependencies. And there's probably a bunch of people using this template currently who then try to update dependencies on their own and run into something along these lines. Dunno if removing the exclude node-modules config and/or switching to `rollup-plugin-terser`,  or just dropping legacy browser support for the template is the most appropriate move, but I hope this is a helpful note for someone! 😊

**Comment by Rich-Harris** [comment]
Thanks — I decided to just remove Bublé altogether (nowadays it's really only necessary for IE11 support, which I don't think this template needs to be concerned with) and swapped Uglify out for Terser which is an actively maintained fork.
