### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by nicreichert** [sveltejs/template#60]
Hey,

I was checking out the project, and, while testing the app (after only installing dependencies and running `yarn dev`), I noticed it's not working on safari at all. 

I didn't have a lot of time to dig in this, but, for some reason, the `bundle.js` file is imported with the content of the `index.html`, which causes a parsing error. It's only happening on Safari, though. 

I thought I'd report it. If I get the chance, I'll check the code and try to open some PR. 

Thanks

**Comment by macropp** [comment]
I think it's just a serving problem. All the files are generated as expected. I tried serving the public folder with `lite-server` and it worked fine.
