### ISSUE TITLE
Livereload broken

### ISSUE THREAD

**Issue by Havegum** [sveltejs/template#63]
Livereload does not work with this template as of the lastest livereload version 0.8.1.

To replicate, run
```
npx degit sveltejs/template bugtest
cd bugtest
npm install
npm run dev
```

Then open your browser at localhost:5000 and edit the svelte project in your editor. Changes does not automatically reload the page.

Editing the package-lock.json by replacing the livereload entry with `"livereload": { "version": "0.8.0" }` worked for me.

**Comment by makeable** [comment]
https://github.com/thgh/rollup-plugin-livereload/pull/25
