### ISSUE TITLE
Please help! error ! could not find commit hash for master

### ISSUE THREAD

**Issue by siddagra** [sveltejs/template#68]
I have already checked other threads but I am not sure how to fix this, I tried out a few things, but it did not work please help

``
C:\Users\Admin\Desktop>npx degit sveltejs/template svelte-app
! could not find commit hash for master
``

this library seems amazing please help so I can use it. I am a noob when it comes to nodejs. Have been web developing in html+css+js up till now.

**Comment by squeal** [comment]
Tl;dr: Solved, pls close.
This nonissue is solved (Issue was installing git on windows needing a restart of cmd to update paths and make cmd aware of git).
Sadly, after finding the solution, @siddagra forgot to close this issue.

**Comment by siddagra** [comment]
Install Git CLI if u want to run this library/compiler on your machine :)
