### ISSUE TITLE
changes to global.css do not trigger live reload

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/template#69]
Changing styles in `global.css` does not trigger a live reload.
Manually refreshing the browser does apply the changes.

**Information about your Svelte project:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome Version 77.0.3865.90

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
macOS 10.14.6

- Svelte version (Please check you can reproduce the issue with the latest release!)
3.12.1

- Whether your project uses Webpack or Rollup
Rollup

**Comment by Conduitry** [comment]
I can't reproduce this, although I'm not on macOS. Editing `public/global.css` is triggering a reload, like changes to any other file in `public` do. If anything, it sounds like this would be an issue for the livereload plugin, which we're relying on to trigger page reloads.
