### ISSUE TITLE
included rollup-plugin-terser chokes on some scripts

### ISSUE THREAD

**Issue by halfnelson** [sveltejs/template#74]
https://svelte.dev/repl/c346befcf70c48c6a11e00c48beba393?version=3.12.1 when downloaded and built with `npm run build` results in the error
```
Uncaught ReferenceError: Cannot access 'n' before initialization
```
This was tracked down to be a terser problem that is resolved by going to latest version

**Comment by QuantumInformation** [comment]
Nice one
