### ISSUE TITLE
Add rollup plugins with Livereload and serve 🤫

### ISSUE THREAD

**Issue by chinanf-boy** [sveltejs/template#8]
### 1. package.json Add plugins and Clean scripts

"rollup-plugin-livereload": "^0.6.0"
"rollup-plugin-serve": "^0.4.2",

> clean `serve` , or even `npm-run-all` if you want

``` json
{
  "name": "svelte-app",
  "version": "1.0.0",
  "devDependencies": {
    "npm-run-all": "^4.1.3",
    "rollup": "^0.58.2",
    "rollup-plugin-buble": "^0.19.2",
    "rollup-plugin-commonjs": "^9.1.3",
    "rollup-plugin-livereload": "^0.6.0",
    "rollup-plugin-node-resolve": "^3.0.3",
    "rollup-plugin-serve": "^0.4.2",
    "rollup-plugin-svelte": "^4.0.0",
    "rollup-plugin-uglify": "^3.0.0",
    "svelte": "^2.6.0"
  },
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w"
  }
}
```

### 2. Add plugins to `rollup.config.js`

``` js
import serve from 'rollup-plugin-serve'
import livereload from 'rollup-plugin-livereload'
// ...

		production && uglify(),
		serve("public"),      // index.html should be in root of project
    	livereload("public")
```

## Already Done Demo❤️

https://github.com/chinanf-boy/try-svelte-my-new-project-templete

### <kbd>you Edit the repo after you try</kbd> or `maybe I pull`

**Comment by mikejav** [comment]
Or you can just remove `sirv-cli` and install [browsersync](https://www.browsersync.io/docs/command-line):
```text
npm uninstall sirv-cli
npm install browser-sync --save-dev
```
then just replace `start` scripts in package.json:
```json
"start": "browser-sync public -w --no-ghost-mode",
"start:dev": "browser-sync public -w --no-ghost-mode"
```


✺◟( ͡° ͜ʖ ͡°)◞✺

**Comment by frederikhors** [comment]
@mikejav, @chinanf-boy, can we close this issue if https://github.com/sveltejs/template/pull/22 gets merged?

**Comment by mikejav** [comment]
sure

**Comment by chinanf-boy** [comment]
ok
