### ISSUE TITLE
npm run dev doesn't work

### ISSUE THREAD

**Issue by heberqc** [sveltejs/template#80]
Since the last commit (66cb32c6fc81ef171ec571a71a5adc46e12c944e) in the master branch, the script `npm run dev` show this:

```
> svelte-app@1.0.0 dev C:\dev\svelte\hola
> rollup -c -w

rollup v1.25.2
bundles src/main.js → public\bundle.js...
LiveReload enabled
created public\bundle.js in 273ms

[2019-10-23 10:40:14] waiting for changes...
{ Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'run', 'start:dev' ] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 dev: `rollup -c -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-app@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-10-23T15_40_14_992Z-debug.log
```

I tried with `npm run build` and then `npm run start:dev` but autobuild and autorefresh neither work.

Yesterday (10/22/2019), every had been worked well.

**Comment by Conduitry** [comment]
Sorry about that, I didn't test on Windows. Just pushed a change - can you give that a shot please?

**Comment by heberqc** [comment]
Here is a shot, using cmder:

![image](https://user-images.githubusercontent.com/5299310/67413972-cf5ed700-f587-11e9-979a-605238a14c41.png)

**Comment by Conduitry** [comment]
Did you clone from the updated version of the template? Does your `rollup_start_dev.js` have `spawn: true` in it? This is working for me now on Windows.

**Comment by dkondrad** [comment]
@Conduitry, launches fine for me on Node v12.13.0 with `shell: true` option.
![image](https://user-images.githubusercontent.com/5039735/67415842-beb45e00-f593-11e9-8a99-8c522ade86b8.png)

**Comment by heberqc** [comment]
Yes, now, it works well now (with the commit 724510f4f9458ee043698e2787e1773508a2182b):

![image](https://user-images.githubusercontent.com/5299310/67416415-6fb6fa80-f58c-11e9-901f-9bae0696df6a.png)

![image](https://user-images.githubusercontent.com/5299310/67416470-80677080-f58c-11e9-840a-8dada7ba82a7.png)

Thanks!

**Comment by LuisOcasio** [comment]
Running this install fixed this for me.

npm i rollup

https://www.npmjs.com/package/rollup
