### ISSUE TITLE
No default lang-attribute

### ISSUE THREAD

**Issue by J-Kallunki** [sveltejs/template#85]
**Describe the bug**

Template does not contain default lang attribute or information to define lang-attribute

https://www.w3.org/TR/WCAG20-TECHS/H57.html

**Logs**
```
<!doctype html>
 <html>
 <head>
```

**To Reproduce**

```
npx degit sveltejs/template my-svelte-project
cd my-svelte-project
npm install
npm run dev
```

**Expected behavior**
```
<!doctype html>
 <html lang="en">
 <head>
```

**Information about your Svelte project:**
- Your browser and the version: Chrome 78.0.3904.87

- Your operating system: OS X 10.14.6

- Svelte version: 3.14.1

**Severity**

Serious accessibility issue

**Comment by Rich-Harris** [comment]
thanks — fixed
