### ISSUE TITLE
sirv-cli dependency

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/template#91]
Couldn't this be a devDependency instead of a dependency?
I'm used to telling people that Svelte apps have no runtime dependencies.
This breaks my story. ;-)

**Comment by mvolkmann** [comment]
I just saw a commit that this was done for the benefit of Heroku. Is this something unique to Heroku?

**Comment by frederikhors** [comment]
I think it should be in dev dep too.

Heroku users will find a fix.
