### ISSUE TITLE
could not fetch remote https://github.com/sveltejs/template

### ISSUE THREAD

**Issue by ypliypli** [sveltejs/template#96]
![image](https://user-images.githubusercontent.com/14327002/69492686-a0b68200-0ee0-11ea-993d-e9901f0897dd.png)
![image](https://user-images.githubusercontent.com/14327002/69492741-23d7d800-0ee1-11ea-821b-35ace701438c.png)

**Comment by mvllow** [comment]
<img width="682" alt="Screen Shot 2019-11-24 at 3 35 50 AM" src="https://user-images.githubusercontent.com/1474821/69492711-842c3280-0e6b-11ea-8450-fb3e4d5f4e84.png">

Doesn't seem to be an issue with the repo. See https://github.com/Rich-Harris/degit/issues/37 for possible solutions.

**Comment by hyperkai** [comment]
You need to install `git`:

`sudo apt install git
`

**Comment by tkdphoenix** [comment]
I had this issue because I had accidentally started a git repo in the wrong place (in my projects directory) and once I removed that `.rm -rf .git`  and also a .DS_Store file (mac specific, sorry), I had no issue getting the app to create.
