### ISSUE TITLE
npm run dev does not start server, but does not throw any errors

### ISSUE THREAD

**Issue by BujarMurati** [sveltejs/template#99]
**Steps to reproduce:**

As per [https://svelte.dev/blog/the-easiest-way-to-get-started](https://svelte.dev/blog/the-easiest-way-to-get-started)
`npx degit sveltejs/template my-svelte-project`
`cd my-svelte-project`
`npm install`
`npm run dev`

System Information:
Windows 10, same behaviour occured in both Git Bash and CMD.

**Expected behaviour:**

A dev server should start listening to localhost:5000

**Actual behaviour:**

Screenshot:
![image](https://user-images.githubusercontent.com/39311213/69893798-fa6ee000-1316-11ea-8922-2a565fa27509.png)
`npm run dev ` runs and exits silently. 
No errors are being thrown. Requests to localhost:5000 return ERR_CONNECTION_REFUSED

**Additional information**

I looked at issue #80 where a file called `rollup_start_dev.js` is mentioned. There is no such file (as verified with `dir rollup_start_dev.js \s` not finding the file) in my project directory + subdirectories.

**Comment by ebauger** [comment]
I had the same issue on macos 10.15.1 

`etienne@MBP-de-Etienne ~/lindex-inscription [master *]
± % npm run dev                                                                                        !2712

etienne@MBP-de-Etienne ~/lindex-inscription [master *]
± % npm -v                                                                                             !2713
6.13.1

etienne@MBP-de-Etienne ~/lindex-inscription [master *]
± % node -v                                                                                            !2714
v12.12.0

etienne@MBP-de-Etienne ~/lindex-inscription [master *]
± %   `

**Comment by TehShrike** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1141869/70020925-69854800-1554-11ea-8635-fae2f5ea7acd.png">

**Comment by Conduitry** [comment]
`npm run build` is necessary before `npm run start`, but should not be necessary before `npm run dev`.

I can't reproduce the behavior in this ticket.

**Comment by crinne** [comment]
Ran into same problem (Mac OS X 10.15.1).
Is there workaround for this?

**Comment by prashanth1k** [comment]
Did you set npm ignore-scripts?

Check config and set 'ignore-scripts' to false. 
`npm config set ignore-scripts false`

Ran into the same problem today and that was the issue (did not quite remember that since I don't quite use Svelte regularly).

Webpack does not have this issue. You can go that route if you want to continue ignoring scripts! 
`
npx degit sveltejs/template-webpack svelte-webpack
npm i
npm run dev
`

**Comment by crinne** [comment]
@prashanth1k thank you 
this one helped > `npm config set ignore-scripts false`

**Comment by matthewsparks1975** [comment]
None of the solutions are working for me.  Tried the webpack install as well.  Still getting issues.

**Comment by Zaphod101010** [comment]
If people have ignore-scripts set to true, it's probably because of this vulnerability.

https://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability

**Comment by ebauger** [comment]
Hi, it solves for me.

My env on osx was set with `npm config set ignore-scripts false`

I will open an issue for the vulnerability flag by @Zaphod101010

**Comment by reld** [comment]
> If people have ignore-scripts set to true, it's probably because of this vulnerability.
> 
> https://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability

True that! 
My npm also has ignore-scripts set to false as a security measure!
Is there a workaround for this so we can leave ignore-scripts set to false?
Thank you!

**Comment by Conduitry** [comment]
Closing, as it seems that having `ignore-scripts` enabled is the most likely cause of this. If anyone has further problems, please ask on the Discord server, as GitHub is not the best place to help you debug environmental problems.

**Comment by juliankoehn** [comment]
Same `missing error` but with ignore-scripts disabled.

Steps before:
```
mkdir shop-svelte
npx degit sveltejs/template .
node scripts/setupTypeScript.js
```

```
  shop-svelte npm config get ignore-scripts
false
➜  shop-svelte npm run dev

> svelte-app@1.0.0 dev [...path]/shop-svelte
> rollup -c -w

➜  shop-svelte npm run build

> svelte-app@1.0.0 build [...path]/shop-svelte
> rollup -c


src/main.ts → public/build/bundle.js...
(!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
created public/build/bundle.js in 2s
➜  shop-svelte npm run dev

> svelte-app@1.0.0 dev [...path]/shop-svelte
> rollup -c -w
```

```
Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G13035)
      Kernel Version: Darwin 17.7.0
      Boot Volume: High Sierra
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 40 days 10:05
```

**Comment by tettusud** [comment]
> Same `missing error` but with ignore-scripts disabled.
> 
> Steps before:
> 
> ```
> mkdir shop-svelte
> npx degit sveltejs/template .
> node scripts/setupTypeScript.js
> ```
> 
> ```
>   shop-svelte npm config get ignore-scripts
> false
> ➜  shop-svelte npm run dev
> 
> > svelte-app@1.0.0 dev [...path]/shop-svelte
> > rollup -c -w
> 
> ➜  shop-svelte npm run build
> 
> > svelte-app@1.0.0 build [...path]/shop-svelte
> > rollup -c
> 
> 
> src/main.ts → public/build/bundle.js...
> (!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
> created public/build/bundle.js in 2s
> ➜  shop-svelte npm run dev
> 
> > svelte-app@1.0.0 dev [...path]/shop-svelte
> > rollup -c -w
> ```
> 
> ```
> Software:
> 
>     System Software Overview:
> 
>       System Version: macOS 10.13.6 (17G13035)
>       Kernel Version: Darwin 17.7.0
>       Boot Volume: High Sierra
>       Boot Mode: Normal
>       Secure Virtual Memory: Enabled
>       System Integrity Protection: Disabled
>       Time since boot: 40 days 10:05
> ```
> 
> Starting `rollup -c -w` from terminal results in:
> `Error: listen EADDRINUSE: address already in use :::35729`
> 
> which is related to [thgh/rollup-plugin-livereload#31](https://github.com/thgh/rollup-plugin-livereload/issues/31) - `rollup-plugin-livereload` shipped with svelte template is `^1.0.0` -> after updating to `1.3.0` i had still this error.
> 
> running `lsof -i TCP:35729 | grep LISTEN` exposed an docker process ;O
> 
> ## Solution:
> As `yarn dev`or `npm run dev` is not giving any error, run `rollup -c -w` directly and check if the port is somehow in use.
> 
> ### Error is not Svelte related
> Should be discussed in https://github.com/thgh/rollup-plugin-livereload

This should be the solution, check if the port is already in use, its silently failing

**Comment by crsayen** [comment]
If anyone is still having issues after tryin these solutions see: https://github.com/thgh/rollup-plugin-livereload/issues/51

changing to `!production && livereload({ watch: 'public', port: 35730 })` solved my problem. Seems livereload will swallow errors stemming from port conflicts

**Comment by LuisOcasio** [comment]
Running this install fixed this for me. 

npm i rollup

https://www.npmjs.com/package/rollup

**Comment by antony** [comment]
As per the currently open issue which pertains to this, the unmerged PR here https://github.com/thgh/rollup-plugin-livereload/pull/24 will fix this - /cc @thgh
